version: '3'

services:
  rabbitmq :
    networks:
      - mynetwork
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "pass"
    ports:
      - "15672:15672"
  node:
    networks:
      - mynetwork
    image: node-app
    build:
      context: ./node
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: pass

  dispatcher:
    networks:
      - mynetwork
    ports:
      - "8080:8080"
    image: dispatcher-app
    build:
      context: ./dispatcher
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: pass

networks:
  mynetwork:

